</div><form action="http://localhost/automate/questions.php?submitted" method="post" enctype="multipart/form-data" accept-charset="utf-8" id="responseform"><div><div id="question-29432467-7" class="que multichoice deferredfeedback notyetanswered"><div class="info"><div class="d-flex align-items-center flex-wrap mb-sm-2 mb-md-0"><h4 class="h3 w-100 mb-2">Question <span class="rui-qno">1</span></h4><div class="d-inline-flex align-items-center flex-wrap"><div class="state mr-2 my-2">Not yet answered</div></div></div><div><div class="questionflag mb-sm-2 mb-md-0 mx-md-2 editable d-inline-flex" aria-atomic="true" aria-relevant="text" aria-live="assertive"><input type="hidden" name="q29432467:7_:flagged" value="0"><input type="checkbox" id="q29432467:7_:flaggedcheckbox" name="q29432467:7_:flagged" value="1"><input type="hidden" value="qaid=272184898&amp;qubaid=29432467&amp;qid=1470217&amp;slot=7&amp;checksum=34fe0c38b134ddcc768527a104ee4c64&amp;sesskey=VWl5J6COz2&amp;newstate=" class="questionflagpostdata"><label id="q29432467:7_:flaggedlabel" for="q29432467:7_:flaggedcheckbox"><img src="https://bcpeducollege.elearningcommons.com/theme/image.php/alpha/core/1740076289/i/unflagged" alt="" class="questionflagimage" id="q29432467:7_:flaggedimg"><span>Flag question</span></label>
</div></div></div><div class="content"><div class="formulation clearfix"><h4 class="accesshide">Question text</h4><input type="hidden" name="q29432467:7_:sequencecheck" value="1"><div class="qtext">Which decision-making tool helps evaluate and prioritize different options based on specific criteria?</div><fieldset class="ablock no-overflow visual-scroll-x"><legend class="prompt h6 font-weight-normal sr-only"><span class="sr-only">Question 1</span> Answer</legend><div class="answer"><div class="r0"><input type="radio" name="q29432467:7_answer" value="0" id="q29432467:7_answer0" aria-labelledby="q29432467:7_answer0_label"><div class="d-flex w-auto" id="q29432467:7_answer0_label" data-region="answer-label"><span class="answernumber">a. </span><div class="flex-fill ml-1">Root Cause Analysis</div></div> </div>
<div class="r1"><input type="radio" name="q29432467:7_answer" value="1" id="q29432467:7_answer1" aria-labelledby="q29432467:7_answer1_label"><div class="d-flex w-auto" id="q29432467:7_answer1_label" data-region="answer-label"><span class="answernumber">b. </span><div class="flex-fill ml-1">Brainstorming</div></div> </div>
<div class="r0"><input type="radio" name="q29432467:7_answer" value="2" id="q29432467:7_answer2" aria-labelledby="q29432467:7_answer2_label"><div class="d-flex w-auto" id="q29432467:7_answer2_label" data-region="answer-label"><span class="answernumber">c. </span><div class="flex-fill ml-1">Decision Matrix</div></div> </div>
<div class="r1"><input type="radio" name="q29432467:7_answer" value="3" id="q29432467:7_answer3" aria-labelledby="q29432467:7_answer3_label"><div class="d-flex w-auto" id="q29432467:7_answer3_label" data-region="answer-label"><span class="answernumber">d. </span><div class="flex-fill ml-1">SWOT Analysis</div></div> </div>
</div><div id="q29432467:7_clearchoice" class="qtype_multichoice_clearchoice sr-only" aria-hidden="true"><input type="radio" name="q29432467:7_answer" id="q29432467:7_answer-1" value="-1" class="sr-only" aria-hidden="true" checked="checked"><label for="q29432467:7_answer-1"><a tabindex="-1" role="button" class="btn btn-link ml-3 mt-n1" href="#">Clear my choice</a></label></div></fieldset></div></div></div><div class="submitbtns"><input type="submit" name="next" value="Next page" class="mod_quiz-next-nav btn btn-primary" id="mod_quiz-next-nav"></div><input type="hidden" name="attempt" value="29253624"><input type="hidden" name="thispage" value="0" id="followingpage"><input type="hidden" name="nextpage" value="1"><input type="hidden" name="timeup" value="0" id="timeup"><input type="hidden" name="sesskey" value="VWl5J6COz2"><input type="hidden" name="mdlscrollto" value="" id="mdlscrollto"><input type="hidden" name="slots" value="7"></div></form><div id="connection-error" style="display: none;" role="alert"><p>Network connection lost. (Autosave failed).</p></div>

<?php

    if(isset($_GET['submitted'])){
        echo "Submitted";
    }


    // const courseURL = `http://localhost/automate/questions.php`;
    // await page.goto(courseURL, { waitUntil: "networkidle2", timeout: 60000 });
?>